//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRB_Rail_Timetable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRB_Rail_Timetable.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BICYCLE.
        /// </summary>
        internal static string Bicycle {
            get {
                return ResourceManager.GetString("Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to choose....
        /// </summary>
        internal static string ClickTo {
            get {
                return ResourceManager.GetString("ClickTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the developer.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUSHETE.
        /// </summary>
        internal static string Coushete {
            get {
                return ResourceManager.GetString("Coushete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the description of this application. My name is test. This is a test. Goodbye..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter station....
        /// </summary>
        internal static string EnterStation {
            get {
                return ResourceManager.GetString("EnterStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST TRAIN.
        /// </summary>
        internal static string FastTrain {
            get {
                return ResourceManager.GetString("FastTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST CLASS.
        /// </summary>
        internal static string FirstClass {
            get {
                return ResourceManager.GetString("FirstClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTER CITY.
        /// </summary>
        internal static string InterCity {
            get {
                return ResourceManager.GetString("InterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late:.
        /// </summary>
        internal static string LatePlus {
            get {
                return ResourceManager.GetString("LatePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL.
        /// </summary>
        internal static string LocalTrain {
            get {
                return ResourceManager.GetString("LocalTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by: DukeCSharp.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries were found..
        /// </summary>
        internal static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable internet connection..
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBLIGATORY RESERVATION.
        /// </summary>
        internal static string ObligatoryReservation {
            get {
                return ResourceManager.GetString("ObligatoryReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGIO VOZ.
        /// </summary>
        internal static string RegioVoz {
            get {
                return ResourceManager.GetString("RegioVoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOND CLASS.
        /// </summary>
        internal static string SecondClass {
            get {
                return ResourceManager.GetString("SecondClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end station must be different..
        /// </summary>
        internal static string SelectDiffStations {
            get {
                return ResourceManager.GetString("SelectDiffStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select stations..
        /// </summary>
        internal static string SelectStations {
            get {
                return ResourceManager.GetString("SelectStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarrifes:.
        /// </summary>
        internal static string Tarrifes {
            get {
                return ResourceManager.GetString("Tarrifes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travels.
        /// </summary>
        internal static string Travels {
            get {
                return ResourceManager.GetString("Travels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version: 1.0.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
